### ISSUE TITLE
handling json response

### ISSUE THREAD

**Issue by juliangums** [spatie/laravel-pjax#30]
Symfony\Component\Debug\Exception\FatalThrowableError in GET /applications
Argument 1 passed to Spatie\Pjax\Middleware\FilterIfPjax::filterResponse() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in /.../vendor/spatie/laravel-pjax/src/Middleware/FilterIfPjax.php on line 35

I've noticed the issue has already been raised and closed in #29 but it does not seem to be fixed yet and was closed without any explaination so the bug still seems to be there

**Comment by waclaw66** [comment]
The problem is that **handle** method of class **FilterIfPjax**
`public function handle(Request $request, Closure $next): Response`
returns **Illuminate\Http\Response** which extends **Symfony\Component\HttpFoundation\Response**
but some of other libraries (e.g. laravel-socialite) return response inherited directly from **Symfony\Component\HttpFoundation\Response**
You should update the handle method to return Response type from Symphony which is the most basic class.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by waclaw66** [comment]
There it is... https://github.com/spatie/laravel-pjax/pull/32
> 
> 
> I'd accept a PR that fixes this.

**Comment by freekmurze** [comment]
Thanks!
